### ISSUE TITLE
cycle-time / logs of activity ref WAL-E to S3

### ISSUE THREAD

**Issue by Analect** [mattermost/mattermost-docker#46] opened 2016-08-16 14:27 UTC
Eventhough I'm not using my mattermost installation that much, at present, as I'm still testing, I'm noticing a logging cycle of uploading / archiving to S3 every minute ... (see link below).  Is this normal ... and if so, is there a way to increase the cycle time ... ie. to every 5 mins rather than every minute?

https://gist.github.com/Analect/4fc34398ff874d6172a426b43dd9ddc5

Thanks.

**Comment by npcode** [comment] 2016-08-17 06:28
I can't guess how serious the problem is because I don't use aws. But it sounds reasonable to allow users to configure the cycle time.

/cc @xcompass

**Comment by xcompass** [comment] 2016-08-17 06:50
@Analect 60 seconds is the default value from postgres. See archive_timeout  on https://www.postgresql.org/docs/9.3/static/runtime-config-wal.html#GUC-ARCHIVE-COMMAND. I just sent a PR to customize this option.

**Comment by Analect** [comment] 2016-08-17 12:46
Great. Thanks @xcompass @npcode

**Comment by npcode** [comment] 2016-08-20 07:32
Closed via #47

**Closed by npcode** 2016-08-20 07:32 UTC
