### ISSUE TITLE
Web proxy causing issues when behind another proxy.

### ISSUE THREAD

**Issue by jdoubleu** [mattermost/mattermost-docker#57] opened 2016-10-15 11:23 UTC
Theres a [long issue](https://github.com/mattermost/platform/issues/3944) on the official Mattermost repository pointing out a bug.

I figured out that this isn't a problem with the Mattermost platform itself but with the docker stup provided by this setup.

I used the [`docker-compose` file provided here](https://github.com/mattermost/mattermost-docker/blob/master/docker-compose.yml). Because I'm running multiple applications on my host I set up a reverse proxy. This reverse proxy serves HTTPS to the clients but communicates over HTTP with the backend, so this web proxy isn't using SSL. And there is the point!

By using HTTP in the backend this web proxy detects HTTP and passes it with the `X-Forwared-Proto` header to the Mattermost platform/app where it causes issues (explained in the other thread).

I'm creating a PR with a workaround for this.
For me I just dropped the additional proxy and pass everything from the reverse proxy directly to the Mattermost app.

**Comment by sushruth** [comment] 2016-11-06 16:54
Was having this EXACT issue myself. Thanks a lot for solving it. 

Is there any temporary workaround? (like making those changes in the PR, myself in `nginx.conf` inside mattermost container?)

**Comment by jdoubleu** [comment] 2016-11-06 20:15
> In which case specifying it in docker-compose.yml should help in some way. I will verify and update here if I get through.

Actually this is for the backend. If your backend proxy support https the reveres proxy can cnnect via https to it. This will then pass the correct Protocol in the HTTP headers but you have to configure https for mattermost too.

You can simply drop the web container and pass every request to the app container of the mattermost setup like I did. This is just another proxy to the mattermost app itself.

**Comment by sushruth** [comment] 2016-11-07 13:54
@jdoubleu Thanks! But here is the thing, I want to use the nginx reverse proxy container to manage my subdomains. I am using same SSL certificates for both mattermost container and the proxy container. 

Another observation is that I can access mattermost fine without https, which is the main issue. I can access it using HTTPS (using the IP and not the server name, tested using `curl -k`) from inside the mattermost container itself, also from the nginx proxy container and also from the host operating system. But anything outside that like any other device from within the same physical network, fails in error 500. 

Not sure if any of this information makes sense, But I will post any results I get here just in case anyone may be interested.

**Comment by xcompass** [comment] 2017-02-17 05:11
@sushruth have you resolved this issue? Do you still need any help?

**Comment by alecisec** [comment] 2017-03-01 03:08
Not sure if this is the same issue - but I'm noticing that there's websocket errors due to a missing portion of the nginx configuration. If you are to look at the example on https://docs.mattermost.com/install/install-ubuntu-1604.html or any other page which includes an nginx reverse proxy there's a section - 

   location /api/v3/users/websocket {
       proxy_set_header Upgrade $http_upgrade;
       proxy_set_header Connection "upgrade";
       client_max_body_size 50M;
       proxy_set_header Host $http_host;
       proxy_set_header X-Real-IP $remote_addr;
       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
       proxy_set_header X-Forwarded-Proto $scheme;
       proxy_set_header X-Frame-Options SAMEORIGIN;
       proxy_buffers 256 16k;
       proxy_buffer_size 16k;
       proxy_read_timeout 600s;
       proxy_pass http://backend;
   }

in addition to the  the / location definition

as a result this project will give errors 

 [EROR] websocket connect err: websocket: origin not allowed

on the backend and 

WebSocket connection to 'wss://<mattermost domain>/api/v3/users/websocket' failed: Error during WebSocket handshake: Unexpected response code: 403

from the browser. this is displayed as 

"Please check connection, Mattermost unreachable. If issue persists, ask administrator to check WebSocket port." in a blue banned. 

in line with the current config i would imagine this should be added to 

https://github.com/mattermost/mattermost-docker/blob/master/web/mattermost and https://github.com/mattermost/mattermost-docker/blob/master/web/mattermost-ssl

with this modification -


   location /api/v3/users/websocket {
       proxy_set_header Upgrade $http_upgrade;
       proxy_set_header Connection "upgrade";
       client_max_body_size 50M;
       proxy_set_header Host $http_host;
       proxy_set_header X-Real-IP $remote_addr;
       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
       proxy_set_header X-Forwarded-Proto $scheme;
       proxy_set_header X-Frame-Options SAMEORIGIN;
       proxy_buffers 256 16k;
       proxy_buffer_size 16k;
       proxy_read_timeout 600s;
       proxy_pass http://app:80;
   }

however having made that change myself and restarting the 'web' container the errors persist. I'm unsur of the cause for this.

**Comment by sushruth** [comment] 2017-03-01 14:31
@xcompass I have gone ahead with not using Mattermost at all. Thank you.

**Comment by jdoubleu** [comment] 2017-03-01 18:02
Sorry for the delay!

> But here is the thing, I want to use the nginx reverse proxy container to manage my subdomains. I am using same SSL certificates for both mattermost container and the proxy container.
> 
> [..] But anything outside that like any other device from within the same physical network, fails in error 500.

I don't think this has to do with this fix. This is more a problem with your overall configuration and how you setup your containers, etc.

Like described in the linked PR, my issue only resolved the bug where Mattermost internally detects the wrong URL if it was accessed via http from the reverse proxy no matter how the frontend was configured.

**Comment by xcompass** [comment] 2017-03-02 05:20
@jdoubleu which post?
OK. I'll close this issue for now. Will open if there is any issue.

**Closed by xcompass** 2017-03-02 05:20 UTC

**Comment by xcompass** [comment] 2017-03-02 06:00
@jdoubleu found the post. It seem he/she moved the post into a new issue.
