### ISSUE TITLE
Bucket name contains invalid characters

### ISSUE THREAD

**Issue by Analect** [mattermost/mattermost-docker#68] opened 2016-12-07 15:36 UTC
Having just upgrade from version 3.2 to version 3.5.1, I'm finding the Wal-E set-up against S3 complaining about bucket name.  This wasn't something I was previously aware of.

In the console, I'm getting 500 errors when mattermost tries to get a user's profile image: 
`http://myserver.com:8001/api/v3/users/65k7nxg67t8uzknbzwtzeiqfnc/image?time=1464276885722`

```
{"id":"api.file.write_file.s3.app_error","message":"Encountered an error writing to S3","detailed_error":"Bucket name contains invalid characters.","request_id":"inifyoqwf7rujykh1umnapuuar","status_code":500}
```

In the app, the user profile images are failing.
![image](https://cloud.githubusercontent.com/assets/4063815/20974014/be2a73bc-bc92-11e6-898c-ff6c107703c2.png)

The bucket prefix looks like this:
`WALE_S3_PREFIX=s3://mybucket.mattermost/version_3.0`

As I've said, I used this in earlier versions without a problem.
Can't see any references to this problem on https://github.com/wal-e/wal-e
Any thoughts on what might be going wrong here?

**Comment by jasonblais** [comment] 2016-12-15 07:28
@xcompass Any thoughts on this question?

**Comment by xcompass** [comment] 2016-12-15 08:19
Is there any special characters in your bucket name?

Are you sure the error is triggered by Wal-E? Wal-E is only for backup, not image storage. Also it looks like it is trying to write to S3 from the error message, it doesn't sound like getting profile. Did you setup mattermost to use S3 as storage? It seems the error came from mattermost not wal-e based on the id (api.file.write_file.s3.app_error). https://github.com/mattermost/platform/blob/master/api/file.go#L754

If your bucket have "-" or any other special characters, that might be the cause. Because mattermost platform switched S3 library from goamz to minio-go (https://github.com/mattermost/platform/commit/f02620b291b988848392c455a7719699f6b5c00f) And minio-go doesn't like "-".  (https://github.com/minio/minio-go/blob/d02caa62b9e1034f93a82d41da806651a666c5a3/api-put-bucket_test.go#L145) And maybe some other characters.

**Comment by mtrofimm** [comment] 2017-01-10 00:55
@xcompass I also noticed that it's not possile to include a folder name like `backet/folder` for the `Amazon S3 Bucket` config option. One gets `Bucket name contains invalid characters` then :(

**Comment by xcompass** [comment] 2017-02-17 05:31
Thanks @mtrofimm. It seems you have to use the bucket instead of the subfolder. It could be bug in Wal-E.

**Comment by xcompass** [comment] 2017-06-08 22:34
I'm closing this for now. Let me know if there is any question.

**Closed by xcompass** 2017-06-08 22:34 UTC
