### ISSUE TITLE
ERROR at docker-compose start

### ISSUE THREAD

**Issue by cbeldacap** [mattermost/mattermost-docker#167] opened 2017-09-01 11:03 UTC
I just cloned the repo locally and changed ENV vars in `docker-compose.yml`

When I run the command `docker-compose start` this is what I get:
![image](https://user-images.githubusercontent.com/20857839/29967226-ef4201da-8f15-11e7-97f2-f90db4b63580.png)

Am I missing some pre-configuration?

Thnx in advance

**Comment by pichouk** [comment] 2017-09-01 12:59
Hmm, I never saw this. Did you run `docker-compose` command on the same folder than the `docker-compose.yml` file ?
Seems to be an error with `docker-compose` more than with your configuration. Does it work with another file on this system ?

**Comment by mtrofimm** [comment] 2017-09-07 09:18
@cbeldacap 
system cannot find such a shell:  `#!/bin/bash\r`
because the file has old dos line endings :/
```
$ file docker-entry.sh 
docker-entry.sh: Bourne-Again shell script, ASCII text executable, with CRLF line terminators
```
`dos2unix *` solves this problem :)

**Comment by cbeldacap** [comment] 2017-09-07 10:22
I ran `docker-compose up --build` and images and containers were built. I stopped them because there were some "file or directory not found" issues, and `docker-compose start` them again. They started, but `_app` and `_db` stopped. `_web` is still up, but I don't know how to access it from the browser.

@mtrofimm

**Comment by pichouk** [comment] 2017-09-07 11:51
What is your Docker and Docker Compose version ? Is everything up to date ? Does it work with another `docker-compose.yml` file ? Because it seems to be an internal error of Docker compose

**Comment by cbeldacap** [comment] 2017-09-07 14:21
I think it's quite updated:
![image](https://user-images.githubusercontent.com/20857839/30168020-7a80eee2-93e8-11e7-9f3b-d6dfe6f5a997.png)
![image](https://user-images.githubusercontent.com/20857839/30168027-820ababc-93e8-11e7-8f9a-04b2de409d90.png)

@pichouk

**Comment by pichouk** [comment] 2017-09-07 14:30
I really don't know. I cannot reproduce, it maybe related to `link` instructions but I don't understand why.
What is your OS and `python` version ?

**Comment by pichouk** [comment] 2017-09-07 14:31
OH maybe you use Windows ? If true, I really cannot help you. Just find [someone with the same error on Windows](http://www.cloudypoint.com/Tutorials/discussion/docker-solved-docker-compose-up-gives-the-system-cannot-find-the-file-specified-error/), you can try the solution.

**Comment by cbeldacap** [comment] 2017-09-07 15:21
@pichouk yup, it's Windows10! Actually I don't have Python installed... is it a must here??

**Comment by pichouk** [comment] 2017-09-07 15:37
I'm pretty sure Docker Compose use Python. I don't know how it works on Windows, but you can look at the [installation documentation](https://docs.docker.com/compose/install/#install-compose).

**Comment by pichouk** [comment] 2017-09-19 14:12
Anything new on this ?

**Comment by tonylea** [comment] 2017-09-26 13:19
I experienced this too, running Windows 10. The problem comes from Windows adding CR to the end of each line.  Not an issue for most files, but causes the *.sh files to error out. 

It can be fixed by replacing the CRLF with just LF as detailed in [this blog post](https://blogs.msdn.microsoft.com/stevelasker/2016/09/22/running-scripts-in-a-docker-container-from-windows-cr-or-crlf/)

**Comment by pichouk** [comment] 2017-09-26 13:25
Thanks @tonylea for this solution ! As I'm not a Windows user, I couldn't find this ^^

**Closed by pichouk** 2017-09-26 13:25 UTC

**Comment by cbeldacap** [comment] 2017-09-26 14:53
I just run it on my Linux server and it worked!
